apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: hpfm4dfah-java-quarkus-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/hpfm4dfah-java-quarkus-gitops